---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - rspec-expectations
  - capybara
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
max_files: 5000
